### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by JalilAbdullayev** [tadwohlrapp/udemy-improved-course-library#11] opened 2023-08-14 08:09 UTC
It's a great extension. I use this for a long time but I have a problem on Chrome and Edge now. I can't see any course details. I was using [Chrome Web Store version](https://chrome.google.com/webstore/detail/udemy-improved-course-lib/dmlfcanjgejpgjajoiepgfglmjcnhhlh) on both. Tried to use with [userscript](https://greasyfork.org/en/scripts/402838-udemy-improved-course-library) but nothing changed.

Google Chrome 114.0.5735.199 (Official build) (64-bit)
Microsoft Edge 115.0.1901.203 (Official build) (64-bit)

![udemy_issue](https://github.com/tadwohlrapp/udemy-improved-course-library/assets/55533255/2708726a-1267-4cd7-af0b-3dc39e5c5b1d)

**Comment by tadwohlrapp** [comment] 2023-08-14 08:19
@Jalil02 Thank you for the report, but I'll close this issue now as it's a duplicate of #10

**Closed as not planned by tadwohlrapp** 2023-08-14 08:19 UTC

**Comment by JalilAbdullayev** [comment] 2023-08-14 08:26
I use latest version (1.1.1) but I still have an issue.

**Comment by tadwohlrapp** [comment] 2023-08-22 06:45
> I use latest version (1.1.1) but I still have an issue.

Right, sorry for the late reply, @Jalil02 

v1.1.1 was the affected version and at the time of your comment it was the latest version.

Since then 1.1.2 was successfully released to greasyfork as well as all three add-on stores.
It was documented in issue [#10](https://github.com/tadwohlrapp/udemy-improved-course-library/issues/10) but I just noticed that this issue somehow disappeared and now 404's. Absolutely no idea what happened there.

Anyways, feel free to let me know if you were able to update to 1.1.2 and if this version fixed the issue on your end.

**Comment by JalilAbdullayev** [comment] 2023-08-22 09:21
It worked. Thank you.
